### ISSUE TITLE
The name 'QError' isn't a type and can't be used in an on-catch clause

### ISSUE THREAD

**Issue by mkreatif** [qiscus/qiscus-chat-sdk-flutter#10]
![Screenshot from 2021-03-08 10-51-36](https://user-images.githubusercontent.com/67994579/110272280-64873200-7ffc-11eb-925f-c1cb6ec852c3.png)
Im using qiscus_chat_sdk 1.0.12 when package updated to 1.0.13.. im getting this problem

**Comment by adicatur** [comment]
Hi @marlinakreatif ,

Can we know what function do you call?

Regards

**Comment by mkreatif** [comment]
try {
await qiscus.setup$(APP_ID);
...
...
..
} on QError catch (error) {}

**Comment by apiep** [comment]
Hi sorry, it seems that `QError` object got deleted by accident, this issue is fixed on the latest relase

**Comment by mkreatif** [comment]
thank for update
