### ISSUE TITLE
Qiscus Push Notif Sending Notif to Unregistered Devices

### ISSUE THREAD

**Issue by mkreatif** [qiscus/qiscus-chat-sdk-flutter#11]
saya mau bertanya, kenapa setelah upgrade qiscus-chat-sdk-flutter dari versi 1.0.12 ke 1.0.17, push notifikasi dari qiscus mengirim notifikasi ke device yang tidak terdaftar dalam chatroom ..

**Comment by apiep** [comment]
untuk pertanyaan seperti ini, bisa di tanyakan terlebih dahulu di halaman web qiscus ticketing ya
