### ISSUE TITLE
migrating to null safety

### ISSUE THREAD

**Issue by johnnypramadya** [qiscus/qiscus-chat-sdk-flutter#12]
When this package to start migrating to null safety?

**Comment by apiep** [comment]
Nullsafety definitely interests me, but since nullsafety requires the latest version of flutter to work, and most of our clients are still using a version of flutter that doesn't support nullsafety, I'm afraid this will hinder them to update to a latest relase of qiscus sdk.

Thank you, I will keep this issue open for future reminders

**Comment by samuelg2729** [comment]
Any updates for this? I think you can just keep the old version running alongside with the nullsafety version. Thanks

**Comment by adicatur** [comment]
Hi @samuelg2729 @johnnypramadya we will release next version to support null safety on 8th Nov 2021. We will let you know the update.

**Comment by paperlambda** [comment]
is there any update for the null-safety version release?

**Comment by apiep** [comment]
Hi @paperlambda sorry for the late reply, we have published a beta release for initial null-safety version on [pub.dev](https://pub.dev/packages/qiscus_chat_sdk/versions/2.0.0-beta.1) if there are no issue within a week or two, we will introduce it as a stable release, please give it a go and let us know if there any issue

**Comment by paperlambda** [comment]
> Hi @paperlambda sorry for the late reply, we have published a beta release for initial null-safety version on [pub.dev](https://pub.dev/packages/qiscus_chat_sdk/versions/2.0.0-beta.1) if there are no issue within a week or two, we will introduce it as a stable release, please give it a go and let us know if there any issue

just noticed this recently while revisiting our migration effort. thank you for the support! @apiep
