### ISSUE TITLE
can't use clearMessagesByChatRoomId

### ISSUE THREAD

**Issue by IsaacOmy** [qiscus/qiscus-chat-sdk-flutter#9]
when I use method **clearMessagesByChatRoomId**, 
I got an error "QError: Validation error"

**Comment by AsyrofQiscus** [comment]
Hi IsaacOmy,
Can you give detailed steps and response message?
1.What room ID do you use?
2.What is your appid?
3.What is the complete error response?

Best Regards

**Comment by IsaacOmy** [comment]
HI AsyrofQiscus,

1. roomUniqueIds : [6fe6f714d5eaef6191b4c8306c8cdbfe]
2. appid : is that okay to post appId on public issue ?
3. this what printed on my console log : I/flutter (11492): error QError: Validation error

I follow this sample code from the documentation :
`qiscus.clearMessagesByChatRoomId(
    roomUniqueIds: roomUniqueIds,
    callback: (error) {
      if (error != null) {
        print("error ${error}");
      }
      print('success');
    });`

and I call that func from this page:
https://github.com/qiscus/qiscus-chat-sdk-flutter-sample/blob/master/lib/screen/chat_page.dart

and got an error printed on my console : I/flutter (11492): error QError: Validation error

Regards,
Thank you.

**Comment by AsyrofQiscus** [comment]
Hi IsaacOmy,
Indeed sorry for that, you can send your appid to our ticketing if needed; but for now we will do with your unique room id.

Can you redo the call? we don't get the roomid in our logs.
Also can you debug , before calling what is the roomid?
to make sure it's the correct unique id

Best Regards

**Comment by IsaacOmy** [comment]
HI AsyrofQiscus,

roomid: 33486689

I used this :
uniqueId: e47b8b36ce3e56349bd6281b7052574a

Here the room object (with some censored data):
`QChatRoom(id=33486689, name=Eko Aprianto, uniqueId=e47b8b36ce3e56349bd6281b7052574a, unreadCount=0, avatarUrl=null, totalParticipants=2, extras=null, participants=[QParticipant(id=eko*****@gmail.com, name=Eko Aprianto, avatarUrl=null, lastReadMessageId=null, lastReceivedMessageId=null, extras=null), QParticipant(id=richa@mailinator.com, name=Richa Pratiwiwati, avatarUrl=null, lastReadMessageId=null, lastReceivedMessageId=null, extras=null)], lastMessage=QMessage( id=490165858, text=test, chatRoomId=33486689, sender=QUser(id=richa@mailinator.com, name=Richa Pratiwiwati, avatarUrl=null, extras=null), uniqueId=flutter-1608792991495, type=QMessageType.text, status=QMessageStatus.sent, extras=null, payload=null, timestamp=2020-12-24 06:56:32.576Z, previousMessageId=0), type=QRoomType.single)`

Regards,
Thank you

**Comment by AsyrofQiscus** [comment]
Hi IsaacOmy,
Thank you for the detail.
Can you give us the snippet on how you call the function?
To gain better context.
Best Regards.

**Comment by IsaacOmy** [comment]
HI AsyrofQiscus,

Here's my code :

`  _deleteAllChatInRoom() {
    List<String> rooms = new List();
    rooms.add(room.uniqueId);
    log(rooms.toString());
    qiscus.clearMessagesByChatRoomId(
        roomUniqueIds: rooms,
        callback: (error) {
          if (error != null) {
            print("error ${error}");
          } else {
            Navigator.pop(context);
          }
        });
  }`

anything wrong with my code ?

Regards,
Thank you

**Comment by AsyrofQiscus** [comment]
Hi IsaacOmy,
Thank you for your snippet, it looks fine and has called the function.
We have gotten your API request in our logs and will investigate accordingly.
For this problem we will fix after 4 January 2021 after Qiscus team has fully back in operation.
Due to christmas and new year holidays, our operational at Qiscus is slowing down. Thank you for your attention.

**Comment by IsaacOmy** [comment]
HI AsyrofQiscus,

Thank you for your fast response support,
I'll wait for after 4th January 2021.

Regards

**Comment by AsyrofQiscus** [comment]
Hi IsaacOmy,
We have released version 1.0.7 to handle this.
Kindly please use it.
Best Regards

**Comment by AsyrofQiscus** [comment]
Hi IsaacOmy,
We have released 1.0.8 for further improvement regarding this.
For now we will close this ticket.
Best Regards

**Comment by IsaacOmy** [comment]
Hi AsyrofQiscus,
run good on 1.0.8

Thank you,
Regards
